#!/usr/bin/env bash
# combine.sh — regenerate gordon-christensen.txt, the flattened rule bundle
# for delivery to Claude chat (claude.ai project / custom instructions), where
# the per-file auto-loading of ~/.claude/rules/ is not available.
#
# Verbatim concatenation of README.md + the rule files, in the canonical order
# of the README "Rule index". Re-run after any rule change and commit the
# regenerated gordon-christensen.txt in the same change. See bundle.md.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/gordon-christensen.txt"

# README first, then the rules in canonical index order. Update this list when a
# rule file is added or removed (bundle.md, the bundle-maintenance rule, is
# intentionally excluded — it documents this build, it is not an operating rule
# for the chat audience).
FILES=(
  README.md
  verification.md
  intent.md
  scope.md
  authorization.md
  errors.md
  deviations.md
  public-push.md
  pr-commits.md
  meta.md
  output.md
  loading.md
)

# Fail loudly if a listed file is missing rather than emitting a partial bundle.
for f in "${FILES[@]}"; do
  if [ ! -f "$HERE/$f" ]; then
    echo "combine.sh: missing source file: $f" >&2
    exit 1
  fi
done

{
  echo "gordon-christensen — combined Claude Code operating rules"
  echo
  echo "Generated by combine.sh from the rule source files. Do not edit by hand;"
  echo "edit the source .md files and re-run combine.sh. See bundle.md."
  echo
  for f in "${FILES[@]}"; do
    echo "================================================================================"
    echo "# FILE: $f"
    echo "================================================================================"
    echo
    cat "$HERE/$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines from ${#FILES[@]} files)."
