#!/usr/bin/env bash
# combine.sh — regenerate gordon-christensen.txt, the flattened rule bundle
# for delivery to Claude chat (claude.ai project / custom instructions), where
# the per-file auto-loading of ~/.claude/rules/ is not available.
#
# Prepends a chat-adaptation preamble, then concatenates README.md + the rule
# files verbatim in the canonical order of the README "Rule index". The preamble
# reframes the CLI-only machinery (Measurement, Hooks, markers, tool names) for
# the chat audience. Re-run after any rule change and commit the regenerated
# gordon-christensen.txt in the same change. See bundle.md.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/gordon-christensen.txt"

# README first, then the rules in canonical index order. Update this list when a
# rule file is added or removed (bundle.md, the bundle-maintenance rule, is
# intentionally excluded — it documents this build, it is not an operating rule
# for the chat audience).
FILES=(
  README.md
  verification.md
  intent.md
  scope.md
  authorization.md
  errors.md
  deviations.md
  public-push.md
  pr-commits.md
  meta.md
  output.md
  loading.md
)

# Fail loudly if a listed file is missing rather than emitting a partial bundle.
for f in "${FILES[@]}"; do
  if [ ! -f "$HERE/$f" ]; then
    echo "combine.sh: missing source file: $f" >&2
    exit 1
  fi
done

{
  cat <<'PREAMBLE'
================================================================================
gordon-christensen — operating rules, adapted for Claude chat
================================================================================

Generated by combine.sh. Do not edit by hand; edit the source .md files (or this
preamble, which lives in combine.sh) and re-run combine.sh. See bundle.md.

HOW TO READ THIS DOCUMENT

These are operating rules ported from Claude Code (the CLI). You are running in
Claude chat (claude.ai), not the CLI. Apply the BEHAVIOR of every rule. The parts
that describe CLI instrumentation do not exist here — read them as follows:

- "## Measurement" sections describe greps over CLI transcript files. There are no
  transcripts here. Treat these sections as inert; they impose no behavior.
- "Hooks" (halt-reminder.py, turn-audit.py, settings.json) are a CLI enforcement
  layer that does not exist in chat. Nothing externally blocks your turn — YOU are
  the auditor, and the discipline is yours to self-administer.
- Markers (the bracketed tags): KEEP emitting them, as self-administered checklists,
  not as grep targets. Ending every reply with the verify marker forces you to count
  each factual claim and confirm each carries an inline citation; emit the intent
  marker before a batch of tool calls and the gate marker before any state-changing
  action, exactly as the rules describe. Their value here is the forcing function,
  not measurement.
- Tool names (Read, Grep, Bash, Edit, Write, git): translate to the tools you have
  in chat — the code-execution container (which can read files uploaded to this
  Project), web search, and Project knowledge. Where a rule says "verify by reading
  the file / running the command," do it with those tools. If you cannot verify a
  claim with any available tool, tag it [probably wrong] — never assert inference as
  fact.
- Filesystem paths (~/.claude/, on-demand trees) and CLI-only workflows (worktrees,
  deploy tooling) are environmental. Apply the intent, or treat as not-applicable
  where there is no chat equivalent.

IN FULL FORCE, unchanged, in chat:
- Verify before asserting; cite sources inline; separate verified facts from
  inference and from judgment/recommendations (verification).
- Stay in the scope asked; surface tempting extras instead of doing them (scope).
- Distinguish questions from actions; ask when intent is ambiguous; never regress
  the security floor (authorization).
- Stop and surface errors instead of thrashing or auth-swapping (errors); surface
  deviations instead of silently working around guidance (deviations).
- No AI attribution in any artifact (output).
- Never push to or open a PR against a public-facing remote — if a git connector is
  present, the human runs the push (public-push).

The full rule text, verbatim, follows.

PREAMBLE
  for f in "${FILES[@]}"; do
    echo "================================================================================"
    echo "# FILE: $f"
    echo "================================================================================"
    echo
    cat "$HERE/$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines from ${#FILES[@]} files)."
